name: ZakaWise CI/CD Pipeline

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

jobs:

  # =========================
  # CI PIPELINE
  # =========================
  test:

    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Run tests
      - name: Run Tests
        run: mvn clean test

  # =========================
  # CD PIPELINE
  # =========================
  build:

    needs: test

    runs-on: ubuntu-latest

    # Only run on main branch
    if: github.ref == 'refs/heads/main'

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build JAR
      - name: Build JAR
        run: mvn clean package

      # Upload Artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zakawise-jar
          path: target/*.jar